{
 "title": "marketing dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "google analystics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Action users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "active7DayUsers" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of distinct active users on your site or app within a 7 day period. The 7 day period includes the last day in the report's date range.",
       "label": "7-day active users",
       "value": "active7DayUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "active1DayUsers" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of distinct active users on your site or app within a 1 day period. The 1 day period includes the last day in the report's date range. Note: this is the same as Active Users.",
       "label": "1-day active users",
       "value": "active1DayUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "active28DayUsers" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of distinct active users on your site or app within a 28 day period. The 28 day period includes the last day in the report's date range.",
       "label": "28-day active users",
       "value": "active28DayUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    }
   ]
  },
  {
   "title": "Action users and New users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "newUsers" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
       "label": "New users",
       "value": "newUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "activeUsers" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of distinct users who visited your site or app.",
       "label": "Active users",
       "value": "activeUsers"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    }
   ]
  },
  {
   "title": "Each user generates session and event and view browsing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "sessionsPerUser" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The average number of sessions per user (Sessions divided by Active Users).",
       "label": "Sessions per user",
       "value": "sessionsPerUser"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "eventCountPerUser" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The average number of events per user (Event count divided by Active users).",
       "label": "Event count per user",
       "value": "eventCountPerUser"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "screenPageViewsPerUser" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The number of app screens or web pages your users viewed per active user. Repeated views of a single page or screen are counted. (screen_view + page_view events) / active users.",
       "label": "Views per user",
       "value": "screenPageViewsPerUser"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    }
   ]
  },
  {
   "title": "Average session duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "averageSessionDuration" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The average duration (in seconds) of users` sessions.",
       "label": "Average session duration",
       "value": "averageSessionDuration"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    }
   ]
  },
  {
   "title": "The count of a specific key event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "keyEvents:annotator_submitted" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The count of a specific key event.",
       "label": "Key event count for annotator_submitted",
       "value": "keyEvents:annotator_submitted"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "dimensions": [ "achievementId" ],
     "metrics": [ "eventCount" ],
     "mode": "timeSeries",
     "selectedDimensions": [
      {
       "description": "The achievement ID in a game for an event. Populated by the event parameter `achievement_id`.",
       "label": "Achievement ID",
       "value": "achievementId"
      }
     ],
     "selectedMetrics": [
      { "description": "The count of events.", "label": "Event count", "value": "eventCount" }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "keyEvents:task_reviewed" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The count of a specific key event.",
       "label": "Key event count for task_reviewed",
       "value": "keyEvents:task_reviewed"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    },
    {
     "accountId": "accounts/295352600",
     "cacheDurationSeconds": 300,
     "metrics": [ "keyEvents" ],
     "mode": "timeSeries",
     "selectedMetrics": [
      {
       "description": "The count of key events. Marking an event as a key event affects reports from time of creation. It doesn't change historic data. You can mark any event as key in Google Analytics, and some events (such as `first_open` or `purchase`) are marked as key events by default.",
       "label": "Key events",
       "value": "keyEvents"
      }
     ],
     "selectedTimeDimensions": {
      "description": "The date of the event, formatted as YYYYMMDD.",
      "label": "Date",
      "value": "date"
     },
     "timeDimension": "date",
     "timezone": "Etc/GMT-8",
     "version": "v4",
     "webPropertyId": "properties/418588232"
    }
   ]
  },
  { "title": "twitter,telegram,media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "twitter_followers_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "twitter_followers_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "telegram_group_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "telegram_group_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "media_mentions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "media_mentions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "discord_channel_size_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "discord_channel_size_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Marketing Email reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "hubspot_gauge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      { "expr": "hubspot_gauge", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Email performance reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "hubspot_histogram_report ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      { "expr": "hubspot_histogram_report ", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}