{
 "title": "Mybatis Postgres SQL",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Max SQL query time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(5, mybatis_query_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SQL query time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(mybatis_query_seconds[$__interval])) by (sql)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median SQL query time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(mybatis_query_seconds_bucket[30m])) by (le, sql))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average SQL query time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(mybatis_query_seconds[$__interval])) by (sql)\n/\nsum(count_over_time(mybatis_query_seconds[$__interval])) by (sql)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}